SELECT  'https://web.fulcrumapp.com/records//'+ [FulcrumID]  as mywork_hyperlink
, [MDS_ID]
      ,[FulcrumID]
      ,[AssetID]
      ,[ActionID]
      ,[ActionDescription]
      ,[ActionCategory]
      ,[ActionNotes]
      ,[StartDate]
      ,[Urgency]
      ,[Department]
      ,[Priority]
      ,[StdActionID]
      ,[Status]
      ,[CreatedBy]
      ,[EditDate]
     ,[AppID]
      ,[SyncStatusID]
      ,[ErrorStatusID]
      ,[ErrorMsg]
      ,[Longitude]
      ,[Latitude]
      ,[assigned_to]
      ,[assigned_to_id]
      ,[AttributeID]
  FROM [FulcrumIntegration].[dbo].[MDS]
